### ISSUE TITLE
Error: [$compile:ctreq] Controller 'ngInclude', required by directive 'ngInclude', can't be found!

### ISSUE THREAD

**Issue by allenhwkim** [apparentlymart/node-angularcontext#7]
First, Thanks for this module.

I attempted to compile angular html on the server-side, `angular-template` ,  but later found out, my approach was not that right. Then, I found out this module. All works fine as I expected, but except 'ng-include'. I think I do not know how to set the base path of include files. Your help would be appreciated.

This is my code.
```
$ vi index.js 
var fs = require("fs");
var angularcontext = require('angularcontext');
var context = angularcontext.Context();

context.runFile('spec/lib/angular.js', function(result, error) { 
  if (error) {throw error};
  var $injector = context.injector(['ng']);

  $injector.invoke(
    function($rootScope, $parse, $compile) { 
      var html = fs.readFileSync("spec/test.html", 'utf8');
      var link = $compile(html);
      var element = link($rootScope);
      $rootScope.$apply();
      console.log('$compile test', element.html());

    } 
  );
});
```

and this is my 'spec/test.html'
```
<div>
   <h3>Inline Expression test</h3>
   {{test.inlineExpression}}

   <h3>ng-if test</h3>
   <div ng-if="test.true">Show This</div>
   <div ng-if="test.false">Show This</div>

   <h3>ng-repeat test</h3>
   <ul>
     <li ng-repeat="el1 in test.repeat">
       {{el1}}
       <ul>
         <li ng-repeat="el in el1">{{el2}}</li>
       </ul>
     </li>
   </ul>

   <h3>ng-include test</h3>
   <div ng-include="'spec/include.html'"></div>

   <h3>ng-class test</h3>
   <div ng-class="{blue:test.true}">&nbsp;</div>
   <div ng-class="{green:!test.false}">&nbsp;</div>
</div>
```
Without ng-include, I can see this result successfully
```
$ node index.js 
$compile test 
   <h3>Inline Expression test</h3>
   

   <h3>ng-if test</h3>
   <!-- ngIf: test.true -->
   <!-- ngIf: test.false -->

   <h3>ng-repeat test</h3>
   <ul>
     <!-- ngRepeat: el1 in test.repeat -->
   </ul>

   <h3>ng-include test</h3>
   <!--div ng-include="'spec/include.html'"></div-->

   <h3>ng-class test</h3>
   <div ng-class="{blue:test.true}">&nbsp;</div>
   <div ng-class="{green:!test.false}" class="green">&nbsp;</div>
```

But with `ng-include`, I see the error. and I HAVE `spec/include.html`.

```
$ node index.js 
spec/lib/angular.js:7615
            throw $compileMinErr('ctreq',
                  ^
Error: [$compile:ctreq] Controller 'ngInclude', required by directive 'ngInclude', can't be found!
http://errors.angularjs.org/1.3.17/$compile/ctreq?p0=ngInclude&p1=ngInclude
    at spec/lib/angular.js:63:12
    at getControllers (spec/lib/angular.js:7615:19)
    at nodeLinkFn (spec/lib/angular.js:7804:33)
    at compositeLinkFn (spec/lib/angular.js:7149:13)
    at compositeLinkFn (spec/lib/angular.js:7152:13)
    at publicLinkFn (spec/lib/angular.js:7028:30)
    at /Users/allen/github/angular-template/index.js:36:25
    at Object.invoke (spec/lib/angular.js:4219:17)
    at /Users/allen/github/angular-template/index.js:32:17
    at runSources (/Users/allen/github/angular-template/node_modules/angularcontext/lib/main.js:58:17)
```

My guess is it looks for ng-include file from the base path, but failed.

**Comment by apparentlymart** [comment]
I think something more subtle is going on here.

I've never really used ngInclude since I usually use directives to wrap nested templates, but I studied the ``ngInclude`` directive source code a bit and I think I half-understand what is going on here:

* Internally to Angular there are actually two directives applied whenever you use ``ngInclude``: the ``ngInclude`` directive itself and another "hidden" directive called ``ngIncludeFillContent``. These are both registered with ``$compile`` against the ``ngInclude`` name, but ``ngIncludeFillContent`` has a negative priority.
* The "real" ``ngInclude`` directive includes a no-op controller that has a ``template`` property attached to it that gets set to the template source code once it's loaded.
* The ``ngIncludeFillContent`` directive uses the ``require`` mechanism to get hold of the ``ngInclude`` controller so it can get the template, which it then inserts into the document, compiles, and links.
* Because ``ngInclude`` is a transcluding directive, the ``ngIncludeFillContent`` actually doesn't get called until the transclude is applied, once ``ctrl.template`` is set.

The weird thing here is that once ``ngIncludeFillContent`` is actually linked, Angular can't find the ``ngInclude`` controller on the element. Angular internally implements this ``require`` mechanism by calling ``element.data('ngIncludeCtrl``)``, which inside jQuery and jqLite ends up looking in a special object that's attached to the DOM element as an expando property.

I'm wondering if ``jsdom`` (which is the DOM implementation used inside ``node-angularcontext``) is doing something unusual with its nodes that is preventing the expando mechanism from working correctly.

In most cases where I've used ``node-angularcontext`` we've had jQuery loaded too, preventing the use of Angular's jqLite. Could you try temporarily loading jQuery into your angularcontext and see if that makes any difference? Just like in the browser, you need to load jQuery before Angular to avoid jqLite from being loaded.

Incidentally, you might be interested in a side-project I started a while ago: [Thistle](https://github.com/thistlejs/thistle) is an AngularJS-*inspired* template system that's optimized for server-side use. Whereas AngularJS is written under the assumption that the templates will be compiled and linked on every page load, Thistle assumes we'll compile once and then link many times, and so it does some more aggressive work during compile time for faster linking. The project I was writing it for was cancelled and so I never finished it, and I know there are a few bugs and design quirks in it, but maybe there's something useful in there that you could borrow for your project. I started it because using AngularJS templates with jsdom is pretty CPU-intensive and that was hurting the throughput of our application by stalling the NodeJS event loop.

**Comment by allenhwkim** [comment]
Thanks for the quick holiday reply.
I tried adding jQuery like the following, but no success.
```
context.runMulti(
  ['spec/lib/jquery-2.1.4.js', 'spec/lib/angular.js'],
  ...
);
```
About [Thistle](https://github.com/thistlejs/thistle), I think it has same approach that I have tried, but I might be wrong. I believe Angular is the best html template and thus, it should be compiled(or templated) in Angular way. Although jsdom is cpu-intensive, I would try this way first. 

My main focus is to convert [AngularJS Documentation](https://github.com/allenhwkim/angular-jsdoc) to use Angular template from underscore template so that Angular programmers can contribute easily, and this module is a good match for it at this moment.

**Comment by apparentlymart** [comment]
It would be interesting to see if any other directives that use ``require`` are working. That will tell us if this mechanism is just completely broken with jsdom or whether it's something special about ``ngInclude``.

Some examples of such directives are ``ngSwitchWhen`` (which looks for ``ngSwitch`` on a parent element) and the various form-related directives that look optionally for ``ngModel``. It's pretty hard to test ``ngModel`` here though since the server-side DOM is non-interactive.

For Thistle my goal was to make a template language that has similar syntax and concepts than AngularJS but that isn't required to be 100% compatible. That way it is familiar but isn't forced to implement concepts that are sub-optimal in the server. It actually ended up being quite like the Angular 2.x template system (at least as it was when I created it; I'm sure it's changed since then) rather than the 1.x template system, at least in its implementation... it's nore like 1.x in syntax.

**Comment by allenhwkim** [comment]
@apparentlymart Ended up rewriting of the existing code, https://github.com/allenhwkim/angular-template using https://github.com/allenhwkim/js-template. It works as the same as  https://github.com/thistlejs/thistle tried. I have tried to make as simpler as possible, but that simplicity took time.
